### ISSUE TITLE
Can it support tar.gz package installation and deployment

### ISSUE THREAD

**Issue by zyclove** [clemlabprojects/ambari#1]
Replace the rpm installation package with tar.gz

**Comment by lucasbak** [comment]
Hi, 
Thanks for the issue but are you speaking about Ambari installation or ODP stack deployment ?

**Comment by zyclove** [comment]
ODP stack deployment。

**Comment by zyclove** [comment]
how can we get ODP package? Please provide account information, thank you。
![image](https://user-images.githubusercontent.com/15028279/150099758-dbfc2e2f-4e9f-459d-8408-a56baf099d42.png)
![image](https://user-images.githubusercontent.com/15028279/150099866-598ae457-b4f6-4185-a251-f00314bc6aa8.png)

**Comment by lucasbak** [comment]
Thanks for reporting it
We are going to update the documentation as we do not support tar.gz for Ambari nor the ODP
If you want you can downloads rpms from [here](https://www.clemlab.com/docs/repository-files)

**Comment by zyclove** [comment]
Can you provide the ODP full package download? As our internal network is blocked and cannot be installed through yum repo, thank you。

**Comment by yyounes75** [comment]
Hi @zyclove do you also need the Ambari packages ?

**Comment by lucasbak** [comment]
It's done 👍 @zyclove 
The repos.tar.gz for the stack is now available for version 1.0.3.0-270 [here](https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/odp-release/1.0.3.0-270/repos.tar.gz)
The repos-ambari.tar.gz for Apache Ambari is now available [here](https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/ambari-release/2.7.6.0-162/repos-ambari.tar.gz)

don't hesitate if you need help for using it

Best regards

**Comment by zyclove** [comment]
thanks very much
