### ISSUE TITLE
Feature-Update Spark version to 3.2.x

### ISSUE THREAD

**Issue by BsoBird** [clemlabprojects/ambari#10]
Spark 3.2.X has added many new features, and we hope to use it in production

At present, the spark version under ODP stack is 3.0.x.

**Comment by zyclove** [comment]
We also very much hope to be able to upgrade the spark components.

**Comment by lucasbak** [comment]
Hi,

You can give it a try
https://www.clemlab.com/docs/repository-files

Best regards,

Clemlab team

**Comment by BsoBird** [comment]
Tks

**Comment by zyclove** [comment]
> Hi,
> 
> You can give it a try https://www.clemlab.com/docs/repository-files
> 
> Best regards,
> 
> Clemlab team

The integration speed of spark3.2 is so fast, it's amazing.  

Thank you so much

**Comment by lucasbak** [comment]
Hi,

Looking forward to hear from you

Best regards

Clemlab Team

**Comment by zyclove** [comment]
could you upgrade the spark to 3.2.2 ?  we hope to use it in production.

**Comment by lucasbak** [comment]
Hi,

Here is the link
https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/odp-release/1.0.5.0-4/odp.repo

Give it a try !

Best regards

Clemlab Team
