### ISSUE TITLE
Repository download requires login

### ISSUE THREAD

**Issue by hzhili** [clemlabprojects/ambari#14]
https://archive.clemlab.com/latest/ambari.tar.gz I need to log in, how do I get the account password
![image](https://user-images.githubusercontent.com/39455920/177719180-3974e426-7602-41b2-a622-53398e312bb8.png)

**Comment by lucasbak** [comment]
Hi,

We updated the documentation with 
https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/ambari-release/2.7.6.0-14/repos-ambari.tar.gz

The link was not good,

Best regards,

Clemlab Team
