### ISSUE TITLE
【feat】 Why mapreduce version is  down to 3.2.0 in ODP-1.0.5.0?

### ISSUE THREAD

**Issue by zyclove** [clemlabprojects/ambari#17]
![image](https://user-images.githubusercontent.com/15028279/188362794-842570f8-31bf-4521-ab88-18b133c7f49f.png)

I think， It's better match 3.2.2 with hadoop.

**Comment by lucasbak** [comment]
Hi Zyclove,

I have checked, there is just an error in the VDF generation file step, it's just a display mismatch.
The package is build with 3.2.2 as MR2 is part of Hadoop.

I have made the modification, <service id="MAPREDUCE2-322" name="MAPREDUCE2" version="3.2.2"/>
You can edit manually the VDF file, or wait for the next build, which should be available soon !

Best regards,

Lucas

**Comment by zyclove** [comment]
I see. Thanks.
