### ISSUE TITLE
Is it possible to support the installation and deployment of tar.gz packages of big data components instead of rpm packages

### ISSUE THREAD

**Issue by zyclove** [clemlabprojects/ambari#2]
The operation of compiling rpm packages for big data components is also complicated, and other operating systems, such as Ubuntu, are not supported. The tar.gz package is more flexible to install, and it can also quickly integrate custom installation packages without recompiling rpm packages.

In addition, whether the big data component management script can also be open sourced, we will maintain it together.

Best regards

**Comment by lucasbak** [comment]
Hi,

Closing the issue for now as we are only supporting rpm based installation files and not ubuntu and do not plan to do it.
We will re-open it if we are going to create debian package based installation depending of our clients roadmap.
Best regards,

Clemlab team
