### ISSUE TITLE
【support】How to get odp version 1.2？

### ISSUE THREAD

**Issue by zyclove** [clemlabprojects/ambari#27]
After installing ambari 2.7.8, we can see that odp 1.2 version is already supported.

(https://github.com/clemlabprojects/ambari/tree/2.7.8.0/ambari-server/src/main/resources/stacks/ODP/1.2)

But the official release document did not see the odp 1.2 version information. (https://www.clemlab.com/en/docs/repository-files)
Is the document not updated?
Could you provide it,
Thank you very much.

Best regards

**Comment by lucasbak** [comment]
Hi @zyclove ,

For now Ambari 2.7.8 is still not officially released, that why ODP 1.2 is not either. 
The release date is for October 2023, we are currently testing it.
Ubuntu support will also be added.

Best regards,

Clemlab team

**Comment by zyclove** [comment]
So the odp 1.1.6.0 is latest version ? 
Can this version be used in a production environment? Have you tested or produced the environment?


Best regards

**Comment by lucasbak** [comment]
Indeed ODP 1.1.6.0 is the latest version until ODP 1.2 is released.
 
Yes , you can use it in production.
We have tested it, and is ready for use in production environment.

ODP 1.1.6.0 is based on ODP 1.0.6.0, with in addition Apache Ozone.

Best regards,

Clemlab Team

**Comment by lucasbak** [comment]
Hi @zyclove ,

Can you tell us which version of ambari do you use ?
Is it a fresh installation ?


Best regards,

Clemlab Team

**Comment by lucasbak** [comment]
Hi @zyclove

We are happy to announce that ODP 1.2 and AMBARI 2.7.8.0.0 are released.
You can find spark 3.4.1 build. [Repositories files](https://www.clemlab.com/docs/repository-files).
Give it a try and tell us if you have any problem.

Best regards,

Clemlab Team
