### ISSUE TITLE
【feat】Can flink 1.14 be integrated first?

### ISSUE THREAD

**Issue by zyclove** [clemlabprojects/ambari#3]

**Comment by yyounes75** [comment]
Hi,

We are working on it and will release it as soon as possible.

**Comment by zyclove** [comment]
Excuse me，when is expected to release support？

**Comment by yyounes75** [comment]
Hi,
We are working on best effort to help the community. If you want a quick answer to your request feature you can contact a sale and subscribe to a support package on [clemlab.com](http://clemlab.com/)

**Comment by zyclove** [comment]
Hi, 
Really excited to see that flink has been integrated into ambari version 2.7.7,.
Can you provide the release download address? 
Thank you very much!

**Comment by lucasbak** [comment]
Hi,

Indeed we started working on Flink Integration but it is not yet finished.
We will communicate properly when it is released.
We will update also the official documentation and communicate to you proper adresses for downloading it !

Best regards

**Comment by zyclove** [comment]
I look forward to the new version very much. 
You are a very strong team. We support you as always. 
Thank you very much for your contribution to the community.
