### ISSUE TITLE
ambari版本和原生不一致

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#34]
我看原生的ambari版本目前最高为2.7.7，但是该项目ODP 1.2.1.0版本中写着对应原生版本2.7.8，这是什么原因呢

**Comment by lucasbak** [comment]
Hi,

Yes it is normal.
Commits from original 2.7.8 have been ported back to clemlabprojects/ambari version.

Best regards,

Clemlab Team

**Comment by SGITLOGIN** [comment]
![WX20231121-172111@2x](https://github.com/clemlabprojects/ambari/assets/49664682/1c2ad275-3919-422a-9640-0d0b77bc57e1)
原生ambari githup上显示没有2.7.8版本，只有2.8版本，您上面回复的意思应该是把2.7.7之后的commits推到了clemlabprojects/ambari项目的版本中吧，只是在您这个ambari项目中配置的项目版本是2.7.8，是这个意思吧

**Comment by SGITLOGIN** [comment]
还有一个问题，Kerberos和OpenLDAP在ODP1.2.1.0目前的功能中都还不支持是吗？您这边有没有提供单独的文档能够实现集成Kerberos和OpenLDAP呢

谢谢！

**Comment by lucasbak** [comment]
Hi @SGITLOGIN,

Sorry for the confusion.
Indeed the main official is 2.8 and clemlabprojects is 2.7.8, we have created the 2.7.8 =  2.7.7 + 2.8 commits backport before official 2.8 is released.
We have added ubuntu22 support for ODP 1.2 in 2.7.8 also.
So you can use 2.7.8 from clemlabprojects and have the same security fixes and other patchs as in 2.8.

Kerberos and OpenLDAP are supported.
The following cluster is secured with Kerberos from FreeIPA
![](https://clemlabs.s3.eu-west-3.amazonaws.com/assets/main-ambari-view-dashboard.png)

Best regards,

Clemlab Team

**Comment by SGITLOGIN** [comment]
如果后续有新版本了，ODP平台支持直接在原有集群上升级版本吗？我看官网上没有提供升级操作

**Comment by lucasbak** [comment]
Hi @SGITLOGIN ,

Indeed we are working on the documentation, it lacks kerberization and upgrade but they are both supported.
Kerberization:
- From the Ambari UI, click Admin, and select Kerberos
- Click enable Kerberos and follow the instructions

If you install a cluster from the start, you can select kerberos from the get Started Screen.

**Upgrade**
You need to:
- Install the next release of clemlabprojects/ambari  (using yum/dnf or apt) 
- run ambari-server upgrade with `ambari-server upgrade` command.
Once ambari is upgrade, you can upgrade your cluster usgin the UI and choose express upgrade.

Best regards,

Clemlab Team

**Comment by SGITLOGIN** [comment]
@lucasbak 
好的，非常感谢您的回复
