### ISSUE TITLE
beeline访问hive服务只能使用hive用户

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#39]

**Comment by SGITLOGIN** [comment]
当前集群安装的服务有HDFS、Hive、MapReduce2、Spark3、Tez、YARN、ZooKeeper，没有安装Ranger
目前遇到的问题是使用beeline访问hive服务只能使用hive用户去访问，其他用户访问会报hdfs目录没有权限，如何解决这一问题？
<img width="228" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/c78b661c-f130-4f7c-9b93-aabc6e214238">
使用testuser用户访问
<img width="1237" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/abc7f085-75bd-4e7a-9b6d-38d61eee3db6">
使用hive用户访问
<img width="969" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/75611312-c799-45bc-aab5-226b40ad106f">

**Comment by lucasbak** [comment]
@SGITLOGIN ,

Every user can use beeline, you just need the right authorizations (on Ranger, Hadoop plugin)

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
您的意思是必须安装Ranger，然后进行用户授权后才能做到其他用户去访问是吗

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
您的意思是直接用hdfs dfs -chmod改目录权限是吗

**Comment by lucasbak** [comment]
@SGITLOGIN 

Yes this is it

**Comment by SGITLOGIN** [comment]
好的，明白了，我们有组件能实现管理spark-shell和spark-submit权限吗？

**Comment by lucasbak** [comment]
which version of Ranger do you use ?
It should be compatible

**Comment by lucasbak** [comment]
So ti is compatible as in ODP 1.2 we have Ranger 2.4.0

**Comment by SGITLOGIN** [comment]
我现在想hive集成ldap，但是有两个参数一直是WARN，这两个参数（alert_ldap_username和alert_ldap_password）应该怎么填，如果不填写有什么影响吗？

<img width="1619" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/9ab15b83-ac1f-4d53-8e84-1e23ff5b5d8d">

**Comment by lucasbak** [comment]
You need to provide initial default password when adding Ranger Service

**Comment by lucasbak** [comment]
Did you enter login/password ?

**Comment by SGITLOGIN** [comment]
我的命令行里面加了-p指定了密码

**Comment by lucasbak** [comment]
can you check on ldap side ?

**Comment by SGITLOGIN** [comment]
ldap测试了账号密码，是没有问题的

**Comment by SGITLOGIN** [comment]
先问一下，hive集成ldap，我的配置是没有问题的对吧

**Comment by SGITLOGIN** [comment]
还有一件事？集群是可以开启kerberos认证的吗？我刚才开启kerberos认证失败了，然后禁用kerberos的时候也失败了。

启用kerberos的时候报如下错误，都是在启动zookeeper的时候报错
<img width="1619" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/6a1165ef-4934-462f-aaa7-70a3695e66ca">

<img width="1627" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/3a4e22c5-c853-4dcf-ab49-d3c5f46391e0">

然后我想尝试再去禁用kerberos认证也报错，他也会先启动zookeeper，但是这个时候zookeeper本身就启动不起来
<img width="1611" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/2f1eced9-8d53-4aa3-9420-d2c459a61737">

<img width="1626" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/b3f2b05b-accc-4af1-813c-7995eab12c6f">

**Comment by SGITLOGIN** [comment]
然后现在集群就不能用了，可能又得重新搭建
<img width="1648" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/291c0124-e8a4-4766-a5ee-088620f9c2e9">

**Comment by lucasbak** [comment]
No you should not do this as now you have run the command as root instead of zookeeper
You should look in the logs of zookeeper server

**Comment by SGITLOGIN** [comment]
使用zookeeper也是启动失败
<img width="1108" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/c8095c06-ee16-45c8-b938-434130cbdfff">

<img width="1243" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/92c1eee8-45f0-4339-adcc-78c8329ff872">

<img width="1253" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/80e05c42-bedd-4aea-a6d8-2c7e66cee6a1">

**Comment by lucasbak** [comment]
@SGITLOGIN  can you execute `ls -l /etc/zookeeper/conf`

**Comment by lucasbak** [comment]
everything seems good, you may have problem with your kdc setup

**Comment by lucasbak** [comment]
It's normal, everything looks good
```
lrwxrwxrwx 1 root root 38 Nov 28 09:07 /etc/zookeeper/conf -> /usr/odp/current/zookeeper-client/conf/
root@master01:~# ll /etc/zookeeper/conf/
total 36
drwxr-xr-x 2 zookeeper hadoop    4096 Nov 28 09:17 ./
drwxr-xr-x 3 root      root      4096 Nov 28 09:07 ../
-rw-r--r-- 1 zookeeper hadoop     548 Nov 28 09:07 configuration.xsl
-rw-r--r-- 1 zookeeper hadoop    2481 Nov 28 09:07 log4j.properties
-rw-r--r-- 1 zookeeper hadoop    1284 Nov 28 09:10 zoo.cfg
-rw-r--r-- 1 zookeeper zookeeper  173 Nov 28 09:17 zoo.cfg.dynamic.next
-rw-r--r-- 1 zookeeper hadoop     103 Nov 28 09:10 zookeeper_client_jaas.conf
-rw-r--r-- 1 zookeeper hadoop     608 Nov 28 09:10 zookeeper-env.sh
-rw-r--r-- 1 zookeeper hadoop     221 Nov 28 09:10 zookeeper_jaas.conf
-rw-r--r-- 1 zookeeper hadoop       0 Nov 28 09:07 zoo_sample.cfg

```

**Comment by SGITLOGIN** [comment]
目前这种情况还应该从哪里分析呢？
![image](https://github.com/clemlabprojects/ambari/assets/49664682/3b263a1f-7f6d-48f4-8706-db9bfb63b35a)

**Comment by SGITLOGIN** [comment]
krb5.conf文件是ambari自动生成的，我当时手动应该拷过去了一份/etc/krb5.conf，但是ambari给我覆盖了，应该是我选择启用的kerberos模式导致的
![image](https://github.com/clemlabprojects/ambari/assets/49664682/296a0420-e3c9-4305-9e1f-6c12c88c65f6)

**Comment by lucasbak** [comment]
it's because you need to use FQDN and not shortname, ie master01.clemlab.com instead of master01.
Kerberos does not work with shortname

**Comment by SGITLOGIN** [comment]
跟配置的短域名有关吗？我看kdc里面principal信息也生成了

<img width="388" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/4c15f016-fdde-4ca8-9d0b-14106e9f4e51">

**Comment by SGITLOGIN** [comment]
像之前我们搭建的CDH都没有使用FQDN，而是使用的shortname，也开启了kerberos，并没有什么问题

**Comment by SGITLOGIN** [comment]
按理说也应该是用配置文件中的principal和keyTab去做认证
<img width="521" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/55877666-8354-4328-9665-a72c6296863b">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
测试也是没有问题的
<img width="1587" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/f94425b8-24a6-4b48-a0f2-21835db90337">

**Comment by lucasbak** [comment]
Testing the connection, test just the network but using full qualified domain name is mandatory for kerberos

**Comment by SGITLOGIN** [comment]
我觉得不是安装kerberos必须用full qualified domain name的问题；
有没有可能只是ambari要求的kerberos一定是要用full qualified domain name呢

**Comment by lucasbak** [comment]
Nice, keep us up to date

**Comment by SGITLOGIN** [comment]
我操作系统的版本是CentOS Linux release 7.9.2009 (Core)

**Comment by SGITLOGIN** [comment]
麻烦问一下搭建kerberos时，支持的加密类型应该填写什么，ambari支持什么加密类型？

**Comment by lucasbak** [comment]
you can try this one
aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
有时候在安装集群的时候有一些组件报错，导致后续所有的任务都停了，再然后在首页执行Start all，集群又没有问题了，这种情况会影响组件服务之前的依赖吗？因为我看还有一些check任务还没运行
<img width="1625" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/d2758740-8401-411c-b4a8-39aec75b7cdb">

<img width="1626" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/678ed370-9d82-4c78-b5d0-07880736e3cf">

<img width="1627" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/23b8b2c8-1038-4f18-a6ec-e7c17750527e">

**Comment by lucasbak** [comment]
It can happen. No worries on this subject.
You can start all services it will not affect functionalities.

**Comment by SGITLOGIN** [comment]
这种情况会影响我后续操作吗

**Comment by lucasbak** [comment]
You need to check the logs

**Comment by lucasbak** [comment]
No it will not affect later operations

**Comment by SGITLOGIN** [comment]
您好，我们有微信沟通群吗？

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
您好，这个为什么会有两个版本
<img width="955" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/5e9fe4c9-8c44-43a1-b7b8-d22784b986dc">
<img width="1329" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/61b11091-1074-4913-a42c-01d48885071b">

**Comment by lucasbak** [comment]
Timeline Service v2.0 is optional

**Comment by SGITLOGIN** [comment]
我没有选择过这个组件，应该是ambari自己给我装的，但是现在启用kerberos的时候我看到了Timeline Service有两个版本，Timeline Service V2.0 task成功了，Timeline Service V1.5 task失败了

**Comment by lucasbak** [comment]
Its not a problem, you can remove 2.0 and let 1.5 or remove both services

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
好的，我现在启用kerberos到了最后一步Check Spark3失败了
<img width="1613" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/0a817033-5b13-4994-824e-120b32483c97">

**Comment by SGITLOGIN** [comment]
重试好几次都是报这个问题

**Comment by SGITLOGIN** [comment]
Spark3服务启动失败，HistoryServer日志如下
<img width="1272" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/7bfa3f38-384a-4ac8-8b47-ebf965bb780b">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
Spark3两个服务都启动失败
HistoryServer日志如下
![image](https://github.com/clemlabprojects/ambari/assets/49664682/2702b173-0d74-442a-8372-1c919dbee1dd)

SPARK3 LIVY SERVER日志如下
<img width="1245" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/d8fab2f3-4a2f-47a2-a79a-700019744ef8">

**Comment by lucasbak** [comment]
For Spark History Server, need to check the configuration, we need to reproduce it on our side.
For spark Livy Server, need to check if livy.server. launch.kerberos.keytab exists or to provide it manually. It seems to be a bug we need to reproduce it and work on a solution

**Comment by lucasbak** [comment]
can you show the content of livy.conf ?

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
<img width="622" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/f626990b-7e0c-4af9-85d8-15c5563f0d37">

**Comment by lucasbak** [comment]
@SGITLOGIN 

We reproduced the error.
It's a bug.
The workaround is to specify  `export LIVY_CONF_DIR=/etc/spark3-livy2/conf` in spark3-livy-env variable
<img width="1728" alt="Screenshot 2023-12-08 at 14 08 54" src="https://github.com/clemlabprojects/ambari/assets/4238285/a198d012-8b74-4564-ba5d-5d6855f596d6">

**Comment by lucasbak** [comment]
For SPARK HISTORY SERVER
You need to delete -Dspark.ui.filters from spark3-env content 
<img width="1287" alt="Screenshot 2023-12-08 at 14 13 54" src="https://github.com/clemlabprojects/ambari/assets/4238285/4bc7c448-36db-4408-ae40-42429638939c">


Save and restart the services it will work

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
我这边每次在重启集群的时候，这个服务都报错，这个问题能解决一下吗
![image](https://github.com/clemlabprojects/ambari/assets/49664682/0a126c68-2e11-4645-b88e-d1d9efb41bcc)

**Comment by lucasbak** [comment]
We need to reproduce to work on an improvement but it's not a bug, it depends of the layout of your services.

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
虽然您说这不是错误，yarn依赖了Timeline Service V1.5，目前开启kerberos后，yarn服务中的一直重启失败。
<img width="1598" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/742c1968-a7a0-4c3b-a697-46931d8f6968">
<img width="1218" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/6deae24c-eff4-46f9-a5c6-ac18b323d206">
<img width="1618" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/e224d0f2-44c6-4882-a280-4e91d8dbabf8">
<img width="1625" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/f4a49168-f72a-474f-853e-c2f8b1b76524">
<img width="1670" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/6b77f2f6-cce1-4425-9193-904c543e5ce0">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
除了上面那个问题，还有一个spark问题，spark-shell和spark3-shell执行报错，说是没设置spark home，我应该如何设置spark home，您看以下问题跟设置spark home有关系吗？
<img width="1021" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/6f2b44d1-58db-4d25-a16c-a3d6f4d921b1">

**Comment by lucasbak** [comment]
You can add your env variable in spark-env configuration section

**Comment by lucasbak** [comment]
You need to also regenerate keytabs using Kerberos > regenerate Keytab button (based on your screen shot)

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
我这边临时做了操作export SPARK_HOME=/usr/odp/1.2.1.0-134/spark3，但是spark3-shell用不了
<img width="664" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/81d638ad-61d5-4a80-a0a4-bd7a76886ab0">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
按照您说的，我先重新生成了一下keytab文件（Regenerate Keytabs），目前重启集群时，还是报相同问题
<img width="1597" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/05872a54-c94c-4c64-bc90-84b896053748">

**Comment by lucasbak** [comment]
use the absolut path as a workaround /usr/odp/current/spark3-client/bin/spark-shell

**Comment by lucasbak** [comment]
what are the logs ?

**Comment by SGITLOGIN** [comment]
<img width="426" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/1a5a411e-3be2-43af-806e-d32ebfbbf10e">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
即使使用了绝对路径，还是报错，看打印信息，感觉像是必须使用spark-submit，而没有spark-shell命令一样
<img width="1053" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/fc03eafe-ee1c-48af-aa75-1f325ab1844b">

**Comment by lucasbak** [comment]
can you colocate Yarn Timeline Service 1.5 with Yarn Resource Manager

**Comment by SGITLOGIN** [comment]
TIMELINE SERVICE V1.5 和 TIMELINE SERVICE V2.0 READER两个服务有什么作用，这两个服务在安装YARN的时候能不装吗？不安装这两个服务对集群会有什么影响？

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
目前还有这个问题，spark-shell使用了绝对路径还是报错，看打印信息感觉像是必须使用spark-submit，而没有spark-shell命令一样
![image](https://github.com/clemlabprojects/ambari/assets/49664682/e07ba420-8e01-493d-b709-4119e08e33d6)

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
按理说安装完Spark3服务后，服务器上应该有相关spark home配置，这应该也算是一个问题吗？
export SPARK_HOME=/usr/odp/1.2.1.0-134/spark3
我上面的SPARK_HOME配置的对吗？
<img width="1050" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/68ce479b-44ca-467e-a730-c0000ee21cf5">

**Comment by lucasbak** [comment]
> Timeline Service V1.5放到跟ResourceManager同一台机器就没有问题了，这算是一个bug吗？

It's a requirement !

**Comment by lucasbak** [comment]
> TIMELINE SERVICE V1.5 和 TIMELINE SERVICE V2.0 READER两个服务有什么作用，这两个服务在安装YARN的时候能不装吗？不安装这两个服务对集群会有什么影响？

They are gathering Job metrics they are optional

**Comment by lucasbak** [comment]
> 按理说安装完Spark3服务后，服务器上应该有相关spark home配置，这应该也算是一个问题吗？
> export SPARK_HOME=/usr/odp/1.2.1.0-134/spark3
> 我上面的SPARK_HOME配置的对吗？

Yes it's correct. Yes it should be set by Ambari and not us directly, will need to reproduce

**Comment by SGITLOGIN** [comment]
> > TIMELINE SERVICE V1.5 和 TIMELINE SERVICE V2.0 READER两个服务有什么作用，这两个服务在安装YARN的时候能不装吗？不安装这两个服务对集群会有什么影响？
> 
> They are gathering Job metrics they are optional

您说的可选，是在安装YARN的时候可以把TIMELINE SERVICE V1.5 和 TIMELINE SERVICE V2.0 READER这两个服务删掉是吗？

**Comment by lucasbak** [comment]
Indeed you did not miss a step

**Comment by lucasbak** [comment]
Yes you can delete

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
好的，目前还剩下spark-shell不可用问题，麻烦帮忙分析一下

**Comment by lucasbak** [comment]
It's a identified bug fixed in later version of ODP 1.2. Spark-shell is not rightly rendered
you need to replace `/usr/odp/current/spark3-client/bin/spark-shell` by this file `https://raw.githubusercontent.com/apache/spark/6b1ff22dde1ead51cbf370be6e48a802daae58b6/bin/spark-shell`

**Comment by SGITLOGIN** [comment]
好的，问题已解决

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
ResourceManager UI页面显示401，是需要我在哪儿配置账号密码吗？
<img width="1502" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/20b47656-9251-4164-812a-b1450e5deebb">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
我们这边还有hadoop集成oss的需求，hive数据落地oss，ODP能实现该功能吗？

**Comment by lucasbak** [comment]
can you send the complete screenshot ?

**Comment by SGITLOGIN** [comment]
> @lucasbak 您好 ResourceManager UI页面显示401，是需要我在哪儿配置账号密码吗？ <img alt="image" width="1502" src="https://private-user-images.githubusercontent.com/49664682/289511524-20b47656-9251-4164-812a-b1450e5deebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTIxNDEsIm5iZiI6MTcwMjI5MTg0MSwicGF0aCI6Ii80OTY2NDY4Mi8yODk1MTE1MjQtMjBiNDc2NTYtOTI1MS00MTY0LTgxMmEtYjE0NTBlNWRlZWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEwNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTBjYWJiZDhmODg5MDJiOGUwNzVkOWJmYWZhNmUyNjMwOGVhYzk4NzNjNDFjMDBlMWZiMWIxOGM4OTMwMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N-oyYDeQBTKcvERFRh__y1iOPGIKtbeoyUGDo_bJS8g">

您好已经是页面全部内容了，其他地方没有东西

**Comment by lucasbak** [comment]
the screen shot is not uploaded correctly

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
现在我遇到一个问题，服务器关机重启后，我执行ambari-server restart时，发现zookeeper服务把8080端口占用了，导致我重启ambari-server时报错，三台zookeeper所在的服务器都是显示zookeeper服务已经启动把8080端口占用了，自启动我这边也没有开启，这个是个问题吗？
<img width="1002" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/ea021bbe-07b5-4b50-ac30-2ebf59223c1d">

<img width="1238" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/bf3bc25b-14cd-40bd-9b72-5a7cfff9552c">

<img width="1679" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/e625a9a6-09a9-42f2-a639-f5a13773c59b">

**Comment by SGITLOGIN** [comment]
问题三：我这边安装的是Spark3，昨天替换了spark-shell，当时只是校验了spark-shell是可以进入，但是今天执行sql时会报错。报错如下：
<img width="1044" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/d4789073-5997-438a-95da-44fcda6fdcbe">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好，有时间麻烦看一下以上三个问题

**Comment by SGITLOGIN** [comment]
> 问题三：我布拉格安装的是Spark3，昨天替换了spark-shell，当时只是校验了spark-shell是可以进入的，但是今天执行sql时会报错。报错如下： <img alt="图像" width="1044" src="https://private-user-images.githubusercontent.com/49664682/289737459-d4789073-5997-438a-95da-44fcda6fdcbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjU4NTAsIm5iZiI6MTcwMjM2NTU1MCwicGF0aCI6Ii80OTY2NDY4Mi8yODk3Mzc0NTktZDQ3ODkwNzMtNTk5Ny00MzhhLTk1ZGEtNDRmY2RhNmZkY2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA3MTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZDNmMWU1Yzg0ZTg0MTdhNGMyYzNmOTk2NmI1YTM4YzQzNDY1NTAyYmVhNjdmOWUxNDg0MDljYzdiOTU0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JI6dR4S6FeWblJV1I_DiFF60HwfC0wtsdXQu_fde4Mo">

这个问题我按照https://github.com/clemlabprojects/ambari/issues/15这个issue解决了，但是spark-shell不支持show create table  Hive表，这个怎么解决？
<img width="1236" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/a08fbada-bd97-4cc7-84c2-9665245cdb79">

**Comment by lucasbak** [comment]
1.for ambari and zookeeper on 8080, you can change the port of one of the service
2. for yarn I need to see the upper right page to see which login you are connected with, but if you have kerberos enabled you should configure your browser to use kerberos
3. for spark-sql you should follow documentation https://spark.apache.org/docs/3.4.1/sql-ref.html

**Comment by SGITLOGIN** [comment]
> 1.for ambari and zookeeper on 8080, you can change the port of one of the service 2. for yarn I need to see the upper right page to see which login you are connected with, but if you have kerberos enabled you should configure your browser to use kerberos 3. for spark-sql you should follow documentation https://spark.apache.org/docs/3.4.1/sql-ref.html

改端口仅仅只能保证端口不冲突，但是zookeeper服务在服务器重启后会自动启动起来，这也是一个问题，因为zookeeper服务在服务器重启后自动启动，但是ambari页面上面显示的zookeeper服务是没有启动的，如果我再次从页面上启动zookeeper就会有多个zookeeper的问题

**Comment by SGITLOGIN** [comment]
今天上午我的操作是
1、我重启了服务器，发现8080端口被zookeeper服务占用，导致ambari-server服务启动不起来；
2、我kill掉了ambari-server服务器上的zookeeper进程，此时我没有kill其他两台机器上的zookeeper进程；
3、ambari-server服务启动后，我从页面上看到zookeeper服务是没有启动的；
4、此时我从页面上重启zookeeper服务，发现其他两台机器上的zookeeper服务没有启动起来，ambari-server所处的服务器上的zookeeper启动起来了
5、我把其他两台机器上的zookeeper服务kill掉后，我再次从页面重启zookeeper服务，此时能够启动zookeeper成功。

以上是我上午的操作。

**Comment by lucasbak** [comment]
It's a good solution. You should indeed  separate services on the host, or use different port if you want to run on the same host

**Comment by SGITLOGIN** [comment]
> 1.for ambari and zookeeper on 8080, you can change the port of one of the service 2. for yarn I need to see the upper right page to see which login you are connected with, but if you have kerberos enabled you should configure your browser to use kerberos 3. for spark-sql you should follow documentation https://spark.apache.org/docs/3.4.1/sql-ref.html

@lucasbak 您好
spark-shell不支持show create table Hive表，我执行的命令和您发的官网上是一样，麻烦看一下这个问题
<img width="1240" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/e3773a78-393a-406f-9e13-e6373a8d1182">

**Comment by SGITLOGIN** [comment]
补充截图
<img width="1238" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/d947c26e-c17b-40e4-9e0e-d50fc1988ec3">

**Comment by lucasbak** [comment]
check out if you have hive-site.xml in /etc/spark3/conf, did you follow the documentation by adding the right  jars ?

**Comment by SGITLOGIN** [comment]
> It's a good solution. You should indeed separate services on the host, or use different port if you want to run on the same host

为了让zookeeper端口和ambari-server端口不冲突，我这边想改zookeeper的端口，但是我发现页面zookeeper配置中没有8080端口的配置，页面配置的zookeeper端口就只有2181，这就奇怪了，为什么重启服务器后，会启动一个8080端口的zookeeper服务？
<img width="1438" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/7b06b30d-7e8b-4825-8ab7-bc7da09eb1c6">

**Comment by lucasbak** [comment]
custom-zoo.cfg: admin.serverPort=8081

**Comment by SGITLOGIN** [comment]
这个端口是什么端口，是让我这边把ambari-server的端口改成8081吗？

**Comment by lucasbak** [comment]
it's to change zookeeper colliding port on zookeeper service `custom-zoo.cfg config to modify`

**Comment by SGITLOGIN** [comment]
我刚尝试了一下，8080端口冲突问题确实被解决了，但是zookeeper还是会根据服务器重启并自动启动起来，然后集群重启的时候会报zookeeper启动报错（Address already in use），我感觉你们应该从根本上解决这个zookeeper服务没有设置自启动，但是现象是会根据服务器重启而启动起来的问题。

**Comment by lucasbak** [comment]
You can change it during installation (in the first configuration from the ui), so during the first start you don't have any problem

**Comment by SGITLOGIN** [comment]
不好意思，没看太明白您说的意思，麻烦再给详细说一下吗？
我上面说的报错Address already in use，是指8081这个端口被占用哈，也就是admin.serverPort改成哪个端口，重启后哪个端口就被占用

**Comment by lucasbak** [comment]
An other solution is to disable the admin server.
`admin.enableServer=false` no consequences on functionalities.

**Comment by SGITLOGIN** [comment]
还是将admin.enableServer=false加到custom-zoo.cfg中吗？

**Comment by lucasbak** [comment]
yes

**Comment by BsoBird** [comment]
@SGITLOGIN  Dude, isn't this a French guy? Shouldn't you rather talk to him in English?
