### ISSUE TITLE
zeppelin启动后页面访问失败

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#40]
@lucasbak 您好
zeppelin.interpreter.exclude和zeppelin.interpreter.include参数页面上必须让选择，但是报错是只能选择一个，这个应该怎么解决？
<img width="964" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/c4447f5e-48ed-409f-ac5e-6a34fb4f4043">
<img width="1371" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/c852409a-94ce-41b0-9d11-066c33132f46">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
这个问题也麻烦看一下，谢谢

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
补充问题说明
1、集群开启了kerbberos认证
2、上面问题的截图是zeppelin-zeppelin-ali-hadoop-slave-04.huan.tv.out文件中日志
3、下图为zeppelin-zeppelin-ali-hadoop-slave-04.huan.tv.log文件日志，以及hdfs上/user/zeppelin/conf/目录文件
<img width="1246" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/f0607d37-aac1-4733-b0f3-38d19ab9933a">

<img width="961" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/425f69cc-a341-41ab-915b-f25b49875e25">

**Comment by lucasbak** [comment]
Hi @SGITLOGIN everything seems to work fine, what's the problem ?
