### ISSUE TITLE
Yarn/MR2 service check failed in odp-1.2.1.0-134

### ISSUE THREAD

**Issue by farshad-allahdadi** [clemlabprojects/ambari#44]
Installed zk, hdfs, Yarn, MR2 on a single node. The service check failed for Yarn and Map Reduce with:
java.lang.NoClassDefFoundError: org/apache/hadoop/thirdparty/protobuf/MessageOrBuilder

Fixed by copying jar file to yarn's lib:
cp /usr/odp/1.2.1.0-134/hadoop/share/hadoop/common/lib/hadoop-shaded-protobuf_3_7-1.1.1.jar /usr/odp/1.2.1.0-134/hadoop-yarn/lib/

**Comment by lucasbak** [comment]
Hi @farshad-allahdadi,

We have identified the issue internally.
It is fixed in [AMBARI-83 (clemlab): add common share lib to yarn classpath](https://github.com/clemlabprojects/ambari/commit/fb60aa8e9ab67fb8198c200e85285b68f5e5eb80)

Best regards,

**Comment by farshad-allahdadi** [comment]
@lucasbak That was not included in latest Ambari?
Also I've encountered error while trying to setup LLAP (hive interactive):
[hive@my llap-yarn-service_2024-01-02_07-08-49]$ /bin/bash -c "$JAVA_HOME/bin/java -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true  -Xmx768m  org.apache.hadoop.yarn.service.ServiceMaster -yarnfile hdfs://my.host128.server:8020/user/hive/.yarn/services/llap0/llap0.json -service_name llap0 -D hadoop.registry.zk.root=/registry -D hadoop.registry.zk.quorum=my.host128.server:2181"
Error: Could not find or load main class org.apache.hadoop.yarn.service.ServiceMaster

Could that be also related to this classpath problem?

**Comment by lucasbak** [comment]
@farshad-allahdadi ,

Which version of Ambari do you use ?
Yes it can be related to the classpatch problem.

**Comment by aghazeh** [comment]
Hi @lucasbak 
we use ambari 2.7.8 on ODP1.2-134.
Thanks.

**Comment by lucasbak** [comment]
Hi @aghazeh, which build of ambari ? i.e. `yum info ambari-server` to get the information.

Best regards

**Comment by aghazeh** [comment]
hi @lucasbak 
Last metadata expiration check: 22:58:58 ago on Mon 01 Jan 2024 03:44:28 PM +0330.
Installed Packages
Name         : ambari-server
Version      : 2.7.8.0
Release      : 101
Architecture : x86_64
Size         : 663 M
Source       : ambari-server-2.7.8.0-101.src.rpm
Repository   : @System
From repo    : ambari
Summary      : Ambari Server
URL          : https://www.apache.org
License      : 2012, Apache Software Foundation
Description  : Maven Recipe: RPM Package.

**Comment by lucasbak** [comment]
Hi @aghazeh.

the link for 140 is the good one, however you need to run 
```
systemcl stop ambari-server
yum upgrade ambari-server
ambari-server upgrade
```

However once the cluster is installed, you need to modify the properties manually from the UI. As the database is already populated.

Best regards

**Comment by aghazeh** [comment]
hi @lucasbak 
We used this ambari vertion and we have this problem.
we download link https://clemlabs.s3.eu-west-3.amazonaws.com/centos8/ambari-release/2.7.8.0.0-140/repos-ambari.tar.gz 
but we have this problems

**Comment by aghazeh** [comment]
HI @lucasbak 
ofline repository not update for 140.

**Comment by lucasbak** [comment]
you need to update /etc/yum.repos.d/ambari.repo file to point to 140, or extract the new repos-ambari.tar.gz to new folder

However concerning the classpath you can juste update your yarn-site configuration with the fix we provided. it should work without updating ambari.

Best regards

**Comment by farshad-allahdadi** [comment]
Ambari-2.7.8 140 does not have this problem
