### ISSUE TITLE
ODP 1.2 stacks does not exists in ambari-agent

### ISSUE THREAD

**Issue by Meikelrizkyhartawan** [clemlabprojects/ambari#54]
i'm installing ODP 1.2 using ambari in ubuntu 22, when i try to install the package, the shows error that ODP stack does not exists in /var/lib/ambari-agent/cache/stacks

why the odp stacks does not exists ?

error log : 
Caught an exception while executing custom service command: <class 'ambari_agent.AgentException.AgentException'>: 'Script /var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/application_timeline_server.py does not exist'; 'Script /var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/application_timeline_server.py does not exist'

Command failed after 1 tries

image of error :

<img width="675" alt="image" src="https://github.com/clemlabprojects/ambari/assets/88485337/4a35a01e-6986-47b5-b33e-798a76c95706">

**Comment by lucasbak** [comment]
Hi @Meikelrizkyhartawan,

It must be your ambari-agent which does not communicates correctly with Ambari Server. Check the logs of both services.

Best regards

**Comment by Meikelrizkyhartawan** [comment]
Thanks it was hostname problem
