### ISSUE TITLE
Failed to Start ResourceManager Curl out of memory

### ISSUE THREAD

**Issue by Meikelrizkyhartawan** [clemlabprojects/ambari#55]
im trying to start resource manager after install the odp in ubuntu22 but failed because of curl is out of memory, how to fix this error , i already set the /etc/security/limits.conf and add the setting into unlimited in ~/.bashrc but this error still exists

Free -h show my ram has available space
<img width="498" alt="image" src="https://github.com/clemlabprojects/ambari/assets/88485337/5d82c731-fc2b-4c0f-ba92-8231cdb7ece1">

/etc/security/limits.conf
<img width="271" alt="image" src="https://github.com/clemlabprojects/ambari/assets/88485337/1aaa7536-494e-4561-b47d-5f6375f52ca4">

~/.bashrc
<img width="181" alt="image" src="https://github.com/clemlabprojects/ambari/assets/88485337/65b4a416-9fc2-4042-8ae4-b594c2883958">

Error curl in ambari-server ui
<img width="922" alt="image" src="https://github.com/clemlabprojects/ambari/assets/88485337/b18d357d-3607-4ba5-b73d-104b435e08ba">

Error Logs :
resource_management.core.exceptions.ExecutionFailed: Execution of 'curl -sS -L -w '%{http_code}' -X PUT --data-binary @/var/lib/ambari-agent/tmp/yarn-ats/1.2.1.0-134/hbase.tar.gz -H 'Content-Type: application/octet-stream' 'http://hdp-namenode01.maas.ph:50070/webhdfs/v1/odp/apps/1.2.1.0-134/hbase/hbase.tar.gz?op=CREATE&user.name=hdfs&overwrite=True&permission=444' 1>/tmp/tmp4NHtEg 2>/tmp/tmpYhjVnK' returned 2. curl: option --data-binary: out of memory
curl: try 'curl --help' or 'curl --manual' for more information

when i try to run the command manually it's looks like syntax error am i correct ?
![image](https://github.com/clemlabprojects/ambari/assets/88485337/f1ed4055-d248-4e6a-a327-e5492ba1efaf)

**Comment by Arni82** [comment]
Same error with @/var/lib/ambari-agent/tmp/yarn-ats/1.2.2.0-105/hbase.tar.gz

🤷🏻‍♂️

**Comment by Meikelrizkyhartawan** [comment]
@lucasbak yeah it's work, i change the /usr/lib/ambari-agent/lib/resource_management/libraries/providers/hdfs_resource.py

from this :

cmd += ["--data-binary", "@"+file_to_put, "-H", "Content-Type: application/octet-stream"]

into this :

cmd += ["-F", "data=@"+file_to_put, "-H", "Content-Type: application/octet-stream"]
