### ISSUE TITLE
Obtain the latest version of the installation package

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#61]
Currently known versions
https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/odp-release/1.2.1.0-134/repos.tar.gz
https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/odp-utils/1.2.1.0/repos-utils.tar.gz
https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/ambari-release/2.7.8.0.0-142/repos-ambari.tar.gz

The installation package provided on the official website is not the latest version，Do you currently have the latest version of the installation package available？

**Comment by SGITLOGIN** [comment]
@lucasbak

**Comment by SGITLOGIN** [comment]
@lucasbak Okay, I'll try the latest version

**Comment by SGITLOGIN** [comment]
@lucasbak The installation package version provided on the official website：
https://archive.clemlab.com/centos7/odp-release/1.2.2.0-50/repos.tar.gz
https://archive.clemlab.com/centos7/odp-utils/1.2.2.0-50/repos-utils.tar.gz
https://archive.clemlab.com/centos7/ambari-release/2.7.9.0.0-16/repos-ambari.tar.gz

**Comment by lucasbak** [comment]
@SGITLOGIN 
for utils, we just corrected documentation it's `https://archive.clemlab.com/centos7/odp-utils/1.2.2.0/repos-utils.tar.gz`
