### ISSUE TITLE
Phoenix Query Server failed to start in HBase

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#64]
@lucasbak 
ambari version：2.7.9.0.0-26
odp version：1.2.2.0-105

Cause analysis: The actual script is under /usr/odp/1.2.2.0-105/phoenix-queryserver/bin/queryserver.py, but the queryserver.py script executed during the installation process is in the /usr/odp/1.2.2.0-105/phoenix/bin/ directory Search  , which results in the python script being executed not being found.

The error message is as follows：
<img width="1598" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/59c33f4c-4e6d-4c98-a8e5-622d0ec508e3">

The soft connection of the node where the non-Phoenix Query Server is located is as follows：
<img width="741" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/612d808b-2f07-46e1-be84-cb4679609b81">

The node where Phoenix Query Server is located is softly connected as follows：
<img width="748" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/e0c8d73c-1365-4b1f-9249-3a78e3abbbfc">

**Comment by lucasbak** [comment]
Hi @SGITLOGIN 

Indeed /usr/odp/current/phoenix-server should point to /usr/odp/current/phoenix-server

We are working on reproducing and fixing the issue.

**Comment by lucasbak** [comment]
@SGITLOGIN 

We have succesfully reproduced the issue.
We are fixing and will let you know when it is fixed.

Best regards,

Clemlab Team

**Comment by SGITLOGIN** [comment]
@lucasbak Will this issue with HBase affect the dependent component Altas?

**Comment by lucasbak** [comment]
@SGITLOGIN ,

We have identified the solution.
We are currently testing it and the whole impacts.
It will not affect HBase nor Atlas, as it is a separate package

**Comment by SGITLOGIN** [comment]
OK，Should a new version be released after the problem is fixed？

**Comment by lucasbak** [comment]
Hi @SGITLOGIN ,

Yes the new version release will contains fixes for Phoenix and will come with new ambari version also.

**Comment by SGITLOGIN** [comment]
OK

**Comment by SGITLOGIN** [comment]
@lucasbak 
When is the new version expected to be released?

**Comment by lucasbak** [comment]
@SGITLOGIN ,

this week, we are also bringing some fixes on other component.
