### ISSUE TITLE
Hive external table repair partition takes a long time！

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#65]
@lucasbak 
ambari version：2.7.9.0.0-26
odp version：1.2.2.0-105

Hello, my ODP cluster has been set up. Hive data is stored on oss. It takes a long time to repair the partition of the external table. Why is this? I asked this question before. You said there were no problems with your tests. Have you done any optimization on hive parameters?

## Time to repair partition 271s
<img width="743" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/0975f345-5e2f-4f5c-ae8b-e33dd5bd118c">

## The number of table partitions is 31
<img width="729" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/e72977a9-2c68-40ad-92ba-31c2ce76e9b8">

## Create table statement
<img width="749" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/b7aabdc4-8dc8-48e5-b9f0-9ce144288d63">

**Comment by lucasbak** [comment]
@SGITLOGIN ,

Could you `check the log in hive metastore` while the request is being executed ?

Not at all, we have tested with HDFS (supported FS), not OSS.

**Comment by lucasbak** [comment]
@SGITLOGIN  try to disable stats

**Comment by SGITLOGIN** [comment]
@lucasbak Please give me some guidance on how to operate it, thank you.

**Comment by lucasbak** [comment]
set `hive.stats.autogather=false` un hive-site.xml

**Comment by SGITLOGIN** [comment]
@lucasbak 
hadoop can be integrated with oss, that is, you have not tested hive data on oss, create a hive external table and msck repair tablename, right?

<img width="1561" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/ff87a706-ec8a-4014-8797-7f59de0727ea">

**Comment by SGITLOGIN** [comment]
@lucasbak I tried, changing this parameter has no effect

> set `hive.stats.autogather=false` un hive-site.xml

**Comment by SGITLOGIN** [comment]
@lucasbak 
The solution has been found, just set the hive.metastore.transactional.event.listeners and hive.metastore.event.listeners parameter values ​​to empty.
