### ISSUE TITLE
After Ambari turns on kerberos authentication, yarn/hdfs web ui access error 401

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#66]
@lucasbak 
Hello, Under the premise that kerberos authentication must be enabled, is there any other way to prevent the web ui from being accessed through kerberos authentication？

<img width="1679" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/e3afe246-f7ab-4dc3-88e6-69ec01b78c2e">

**Comment by lucasbak** [comment]
Hi @SGITLOGIN,

If you want to protect your webui you can enable Kerebros on the webui or **proxify your webui using [Apache Knox](https://knox.apache.org)**

**Comment by SGITLOGIN** [comment]
@lucasbak 
My purpose is not to enable security authentication for the web UI and allow everyone to directly access it, so I want to ask if it can be achieved?

**Comment by SGITLOGIN** [comment]
@lucasbak 
Hello, I installed Knox here, but the page can only access https://ali-odp-test-01.huan.tv:8443/gateway/default/yarn/cluster. Clicking Applications cannot access https://ali. -odp-test-01.huan.tv:8443/gateway/default/yarn/cluster/apps page.

<img width="928" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/0f5683d3-3411-4f0e-b593-2d651cfd4e0e">

<img width="1679" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/037dcfeb-daf5-4f9f-8d2b-441990bb59b3">

<img width="1679" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/885056c9-7c88-42aa-9420-de3894060db7">

**Comment by lucasbak** [comment]
@SGITLOGIN ,

its because of your acl in yarn-site put *.

**Comment by lucasbak** [comment]
> @lucasbak Using anonymous access to the web ui as described in the following document will fail when starting HDFS and YARN.
> 
> https://blog.csdn.net/qq_33684569/article/details/116919941?utm_medium=distribute.pc_relevant.none-task-blog-2~default~BlogCommendFromBaidu~default-6.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2~default~BlogCommendFromBaidu~default-6.control

Indeed, it's because Kerberos is stil enable on the cluster and as a consequence, it trie to communicate with NN using kerberos.
It may be an improvement to do on Ambari side.

**Comment by SGITLOGIN** [comment]
@lucasbak 
Which configuration item of my Yarn is configured incorrectly? Please correct it

> @SGITLOGIN ,
> 
> its because of your acl in yarn-site put *.

**Comment by lucasbak** [comment]
@SGITLOGIN 

You can set:
 - yarn.admin.acl: yarn,knox or yarn.admin.acl: *
 
You can also set yarn.acl.enable to false if you want free access to all yarn webuis

**Comment by SGITLOGIN** [comment]
@lucasbak 
I have modified the configuration and restarted the cluster, but the same problem is still reported when accessing the webui page.

yarn.admin.acl=*
yarn.acl.enable=false

**Comment by SGITLOGIN** [comment]
@lucasbak 
Is there any other way?

**Comment by fb-clemlabb** [comment]
Dear SGITLOGIN,

First and foremost, I would like to thank you for your interest in [Your Company Name] and our Open Source Data Platform (ODP) solution. We are thrilled to see the enthusiasm for our product and are convinced of the significant value it can add to your business.

We understand your need for assistance in setting up the ODP cluster and are fully committed to supporting our clients in their success. Our ODP support offering is specifically designed to meet these needs, providing personalized guidance and expert advice to ensure optimal implementation of our solution.

Subscribing to our ODP support offer will give you access to our dedicated team of experts who can assist you with configuration, deployment, and maintenance of your ODP cluster, while offering quick and effective responses to all your technical inquiries. This will not only allow you to maximize the performance of your platform but also ensure the security and sustainability of your data infrastructure.

We are confident that this approach is crucial for leveraging the full potential of our ODP solution and ensuring the success of your project. I would be delighted to discuss your needs in more detail and how our support offering can benefit you. Please do not hesitate to contact me to arrange a meeting or for any further information you may require.

Thank you for your understanding, and I remain at your complete disposal for any questions or clarifications.

Kind regards,
Clemlab Team Support
odp@clemlab.com

**Comment by SGITLOGIN** [comment]
@fb-clemlabb 
OK, we will carefully consider your plan here

**Comment by SGITLOGIN** [comment]
@lucasbak @fb-clemlabb 
Hello，Are there any other solutions to the above web ui problem？
Our purpose is to access the web UI without Kerberos authentication. Simple account and password or anonymous login are acceptable.

**Comment by SGITLOGIN** [comment]
@lucasbak 
I reinstalled the cluster today (this time I tested it on the premise that the Kerberos task was not enabled in the ODP cluster) and found that before turning on the high availability of HDFS and YARN, I could use knox to access yarn's web ui, but after turning on the high availability of HDFS and YARN When I try to access Yarn's web UI later, I get a 403 No Permission error.

HDFS namenode：ali-odp-test-01，ali-odp-test-02
YARN resourcemanager：ali-odp-test-01，ali-odp-test-02
Knox Gateway：ali-odp-test-01

I also tried modifying the yarn.admin.acl=* and yarn.acl.enable=false parameter values, but still reported the same error.

<img width="1667" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/c3708d17-d88b-4ef8-a17d-a4cd532b8a9e">

<img width="902" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/f9dabe86-cc1f-4729-846a-1de0fe26d80b">

**Comment by lucasbak** [comment]
This error comes from Knox acls try to modify also topology default acls

**Comment by lucasbak** [comment]
@SGITLOGIN 

Can you check the authorization part of the `default` topology, also check in core-site `proxy` knox user

**Comment by SGITLOGIN** [comment]
@lucasbak 
The problem that yarn webui cannot be accessed has been solved, but there is a strange phenomenon on yarn webui. Spark type tasks are not displayed on yarn webui. Only the running tasks of the TEZ engine are displayed. However, when running Spark tasks, the top of yarn webui Apps Running also prompts that a task is running. Why is this?

<img width="1679" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/71cf8b9d-6d8d-4dc8-9d0b-8a18256bd564">

<img width="1679" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/eeb206a1-158a-43d0-abe9-213b16786972">

**Comment by SGITLOGIN** [comment]
@lucasbak Hello, the problem I asked above about "the yarn webui page does not display spark type tasks" is a bug in this version of ODP or should this version of hadoop be like this?

**Comment by SGITLOGIN** [comment]
@lucasbak The problem has been resolved.

> @lucasbak Hello, the problem I asked above about "the yarn webui page does not display spark type tasks" is a bug in this version of ODP or should this version of hadoop be like this?

**Comment by lucasbak** [comment]
> @lucasbak The problem that yarn webui cannot be accessed has been solved, but there is a strange phenomenon on yarn webui. Spark type tasks are not displayed on yarn webui. Only the running tasks of the TEZ engine are displayed. However, when running Spark tasks, the top of yarn webui Apps Running also prompts that a task is running. Why is this?
> 
> <img alt="image" width="1679" src="https://private-user-images.githubusercontent.com/49664682/309235895-71cf8b9d-6d8d-4dc8-9d0b-8a18256bd564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDU5MDYsIm5iZiI6MTcwOTU0NTYwNiwicGF0aCI6Ii80OTY2NDY4Mi8zMDkyMzU4OTUtNzFjZjhiOWQtNmQ4ZC00ZGM4LTlkMGItOGExODI1NmJkNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5NDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYjFhN2JkMWVlNjQ0Njk0N2FjNGQxZjk2MGIzNzU3Yjg0MDFkZGY3MTM4MGM4NGY0NzU2NTc3NGY3MWQ4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J9VD5qjDr8XEZ4aWlk_puDV9WGLGGMyZ3tyJn1cTdDY"> <img alt="image" width="945" src="https://private-user-images.githubusercontent.com/49664682/309236665-1193060a-a057-48ec-91aa-d420c4d9e935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDU5MDYsIm5iZiI6MTcwOTU0NTYwNiwicGF0aCI6Ii80OTY2NDY4Mi8zMDkyMzY2NjUtMTE5MzA2MGEtYTA1Ny00OGVjLTkxYWEtZDQyMGM0ZDllOTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5NDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NzM2NDcyNTM4Y2Q5NDdkYWFiYmFmZjU2Y2YwNDliZDM1YmQ2ZTdiNmFmODFlZWExY2E4NzUwNmQ0ZDEzYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jMQoIb8ZB0UXat0dDCuVkDc4BUGiPe21a2F8iRTnX-8">

@SGITLOGIN , there is may be an application running that you do not see because of the acls.

**Comment by lucasbak** [comment]
> @lucasbak Hello, the problem I asked above about "the yarn webui page does not display spark type tasks" is a bug in this version of ODP or should this version of hadoop be like this?

It depends of the tasks, if you are running Hive queries though spark, you will have Hive/Tez taskk type

**Comment by SGITLOGIN** [comment]
@lucasbak 
OK, I have solved this problem in ODP version 1.2.2.0-105 and am installing ODP version 1.2.2.0-127.

**Comment by lucasbak** [comment]
Hi @SGITLOGIN,

Nice to hear !

**Comment by SGITLOGIN** [comment]
@lucasbak 
Currently, knox uses the default ldap in the cluster. but we already have a set of self-built ldap. How should we integrate it? How should I operate it here?
