### ISSUE TITLE
ODP 1.2.2.0-127 version installation error reported

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#67]
@lucasbak 
odp version：1.2.2.0-127
ambari version：2.7.9.0.0-56
Hello, I got an error when installing the new version of ODP --> ”Cannot find postgresql-setup script.“

ambari-server setup --database=mysql --databasehost=****** --databaseport=3306 --databasename=ambari --databaseusername=ambari --databasepassword=Chang1234

<img width="1057" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/625fb829-0fb7-43a9-ae35-b9d7012a6e97">

**Comment by lucasbak** [comment]
Hi @SGITLOGIN,

Please wait for official version and release, as their are some nightly builds.
Can you check if the postgresql dependencies are installed ?

Best regards

**Comment by SGITLOGIN** [comment]
@lucasbak 
I store ambari metadata in mysql, and it has nothing to do with pgsql. Why is this pgsql error reported? How should I avoid this problem?

**Comment by SGITLOGIN** [comment]
@lucasbak 
According to what you said, what dependencies do I need to install for pgsql?

> Hi @SGITLOGIN,
> 
> Please wait for official version and release, as their are some nightly builds. Can you check if the postgresql dependencies are installed ?
> 
> Best regards

**Comment by lucasbak** [comment]
@SGITLOGIN ,

install `postgresql` package.

**Comment by SGITLOGIN** [comment]
@lucasbak 
The postgresql package has been installed, but the same error is still reported

<img width="1061" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/434ae639-5d58-40e5-b7e4-8a66bda6e098">

**Comment by lucasbak** [comment]
Install also `postgresql-server` @SGITLOGIN

**Comment by SGITLOGIN** [comment]
@lucasbak 
There is no problem with ambari-server setup. Old versions do not need to install the pgsql package. Is this a new addition to the new version? I think it is reasonable to prompt this error only when using pgsql.

**Comment by SGITLOGIN** [comment]
@lucasbak 
odp version：1.2.2.0-127
ambari version：2.7.9.0.0-56
Is there any problem with this version? 
Do you mean this version is not a release version?

> Hi @SGITLOGIN,
> 
> Please wait for official version and release, as their are some nightly builds. Can you check if the postgresql dependencies are installed ?
> 
> Best regards

**Comment by lucasbak** [comment]
Hi @SGITLOGIN

There is no problem, with those version no worries

Best regards

> @lucasbak There is no problem with ambari-server setup. Old versions do not need to install the pgsql package. Is this a new addition to the new version? I think it is reasonable to prompt this error only when using pgsql.

Indeed however, as you opened other issue, we remove postgresql package from ambari rpms to be able to install on Amazon Linux 2

**Comment by SGITLOGIN** [comment]
@lucasbak 
OK

> > @lucasbak odp version：1.2.2.0-127 ambari version：2.7.9.0.0-56 Is there any problem with this version? Do you mean this version is not a release version?
> > > Hi @SGITLOGIN,
> > > Please wait for official version and release, as their are some nightly builds. Can you check if the postgresql dependencies are installed ?
> > > Best regards
> 
> @SGITLOGIN No issue with this version no worries

**Comment by SGITLOGIN** [comment]
@lucasbak 
Hello, is there a version change log available.

**Comment by SGITLOGIN** [comment]
@lucasbak 
Does this contain minor version change logs?
for example：ODP version 1.2.2.0-105 --> 1.2.2.0-127

**Comment by SGITLOGIN** [comment]
@lucasbak 
ODP version 1.2.2.0-127
1、When turning on kerberos authentication, there should be something wrong with the service startup sequence. After starting zookeeper, ZKFailoverController is started first. It finds that there is no available datanode, and then an error is reported.
2、Infra Solr service keeps getting stuck when starting
Please try to reproduce it.

<img width="1601" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/a4640a85-fb86-4e60-93c0-ce3ecb256029">

<img width="1558" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/42fba519-43d0-4d7b-8756-0aa0ea76c0fb">

**Comment by SGITLOGIN** [comment]
@lucasbak 
The previous version of ODP 1.2.2.0-105 should also have this problem, but at that time I thought it was caused by my configuration error, and then I restarted each service manually.

**Comment by SGITLOGIN** [comment]
@lucasbak 
Hello, I use knox to proxy other users. When logging in to yarn webui, I use the changguowei account and password to log in. Why is the displayed login user knox？
The page should display the logged-in account. When actually performing other operations, use the knox account to act as the logged-in account, and the permissions should only be the permissions of the logged-in account.

<img width="1679" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/7b6c58b7-5f3a-429e-8f73-4d2930846e2d">

**Comment by SGITLOGIN** [comment]
@lucasbak 
Is this problem a problem with my configuration or is this the way the knox proxy webui looks like?

**Comment by lucasbak** [comment]
Hi @SGITLOGIN ,

It is just a configuration problem, but for this kind of troubleshooting we need to get through support so people can be dedicated for your problem.

> @lucasbak Does this contain minor version change logs? for example：ODP version 1.2.2.0-105 --> 1.2.2.0-127

No changelog it's only stability of build pipeline.

**Comment by SGITLOGIN** [comment]
@lucasbak 
The cluster does not have this issue when it is not enabled for KerberOS. The page displays the logged in user, and this issue occurs after enabling KerberOS authentication. You can replicate it.
