### ISSUE TITLE
spark3-shell fails to submit non-default queue

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#69]
@lucasbak 
I tried to submit the spark task to the non-default queue, and the final task showed failure, but there was no problem with the spark task submitting to the default queue.
Spark task error message：
File does not exist: hdfs://ha-nn/user/changguowei/.sparkStaging/application_1709625801362_0001/__spark_conf__.zip

<img width="1415" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/2dc9d8ad-ca4a-4e1f-be4f-a22659a22ed4">

<img width="1679" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/86431ade-ed16-4ac3-bd63-714087e5500a">

<img width="870" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/3f35edd6-9966-4f1f-b285-b14d7bcdf849">

**Comment by SGITLOGIN** [comment]
@lucasbak 
Hello, are there any solutions to this problem？

**Comment by lucasbak** [comment]
Hi @SGITLOGIN 

Did you add the corrects ACL in Ranger ?
You can use the YARN scheduler Ambari View in order to get proper queue configuration you may have some queue issues.
For this kind of troubleshooting we need to get through support so people can be dedicated for your problem.

Best regards,

Clemlab Team

**Comment by SGITLOGIN** [comment]
@lucasbak 
Ranger permissions are not a problem. I have set up these queues to allow anyone to submit and manage them. Do you suspect that there is an issue with the configuration of my capacity scheduler

**Comment by SGITLOGIN** [comment]
@lucasbak 
The spark3-shell failure to submit non-default queue has been solved. The yarn.scheduler.capacity.resource-calculator I configured is org.apache.hadoop.yarn.util.resource.DominantResourceCalculator, but I see that the default configuration of ODP is org.apache. .hadoop.yarn.util.resource.DefaultResourceCalculator. After I changed it to the default value, there was no problem.

**Comment by SGITLOGIN** [comment]
@lucasbak 
After HDFS turns on high availability, WARN will be reported every time spark3-shell is executed, but it does not affect the subsequent execution of SQL. How to solve this problem?

<img width="1206" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/fc498e8c-33e6-43f8-8bd2-b133eb731062">

<img width="829" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/fe720f8f-79f8-4b3c-9393-db8b1c1545e5">

**Comment by SGITLOGIN** [comment]
@lucasbak 
hello，Can this problem be reproduced?

> @lucasbak After HDFS turns on high availability, WARN will be reported every time spark3-shell is executed, but it does not affect the subsequent execution of SQL. How to solve this problem?
> 
> ACTIVE NAMENODE：ali-odp-test-02.huan.tv STANDBY NAMENODE：ali-odp-test-01.huan.tv
> 
> Each time it is executed, it will first access the namenode of the ali-odp-test-01.huan.tv node to see if it is in the ACTIVE state. If not, it will access the namenode on ali-odp-test-02.huan.tv.
> 
> Before turning on high availability, ali-odp-test-01.huan.tv was the NameNode, and ali-odp-test-02.huan.tv was the SecondaryNameNode.
> 
> <img alt="image" width="1206" src="https://private-user-images.githubusercontent.com/49664682/310410991-fc498e8c-33e6-43f8-8bd2-b133eb731062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzY5MzEsIm5iZiI6MTcwOTc3NjYzMSwicGF0aCI6Ii80OTY2NDY4Mi8zMTA0MTA5OTEtZmM0OThlOGMtMzNlNi00M2Y4LThiZDItYjEzM2ViNzMxMDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkODViOWViMGI0MmQ2Y2E3NzExOWFlNGYxZjg2MzAzMWI2OTdjY2YyZjdjNjdkMjIxMTk2NDBjYmJhYjMwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MGv2UNmtYoxMV_-l8Sb0bvX4D7SnGpPoIX9WqEO25O4"> <img alt="image" width="829" src="https://private-user-images.githubusercontent.com/49664682/310411624-fe720f8f-79f8-4b3c-9393-db8b1c1545e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzY5MzEsIm5iZiI6MTcwOTc3NjYzMSwicGF0aCI6Ii80OTY2NDY4Mi8zMTA0MTE2MjQtZmU3MjBmOGYtNzlmOC00YjNjLTkzOTMtZGI4YjFjMTU0NWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNDAzN2QzZjQwZTJlY2IyZmE0OTYwODAyNmUxN2E0NWMyODdhY2FlYjc5NmM3MjRlYzYzM2Q5ZmQ4Y2Q1NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MM3lOC9SEVacaFtTKtllqyxLOkowYzrS7KlQp8HDhak">

**Comment by SGITLOGIN** [comment]
@lucasbak 
I rebuilt the cluster and found that this problem did not exist before turning on kerberos. This problem appeared after turning on kerberos authentication. I think this is a bug in this version. You can reproduce it.

> @lucasbak After HDFS turns on high availability, WARN will be reported every time spark3-shell is executed, but it does not affect the subsequent execution of SQL. How to solve this problem?
> 
> ACTIVE NAMENODE：ali-odp-test-02.huan.tv STANDBY NAMENODE：ali-odp-test-01.huan.tv
> 
> Each time it is executed, it will first access the namenode of the ali-odp-test-01.huan.tv node to see if it is in the ACTIVE state. If not, it will access the namenode on ali-odp-test-02.huan.tv.
> 
> Before turning on high availability, ali-odp-test-01.huan.tv was the NameNode, and ali-odp-test-02.huan.tv was the SecondaryNameNode.
>

**Comment by lucasbak** [comment]
Hi @SGITLOGIN 

You can have a warning when your HDFS client request the standbay namenode before failing over to active namenode

**Comment by SGITLOGIN** [comment]
@lucasbak 
There was no problem before turning on kerberos authentication. This problem will occur after turning on kerberos authentication. I have tried ODP 1.2.2.0-105 and 1.2.2.0-127 versions, and this problem exists in both versions.

**Comment by SGITLOGIN** [comment]
@lucasbak 
How should I configure the log file to suppress this warning?

**Comment by lucasbak** [comment]
@SGITLOGIN ,

It happens in every version of Hadoop, as it is related to HDFS, You need to update the log configuration file indeed, and also log4back files

**Comment by SGITLOGIN** [comment]
@lucasbak 
Can you provide specific instructions on which part of the log configuration file to modify? Thanks

**Comment by SGITLOGIN** [comment]
@lucasbak 
Can you provide specific instructions on how to handle this issue on your end？

**Comment by lucasbak** [comment]
We need to reproduce it first

**Comment by SGITLOGIN** [comment]
OK

**Comment by SGITLOGIN** [comment]
@lucasbak 
Hello，The reproduction process described in the above problem is not very clear, so I will add some information here.
1. After the namenode is turned on for high availability, ali-odp-test-01.huan.tv is in the ACTIVE state and ali-odp-test-02.huan.tv is in the STANDBY state. At this time, no WARN error will occur when using spark-shell to access it.
2. When the namenode master-slave switchover occurs, ali-odp-test-01.huan.tv is in the STANDBY state and ali-odp-test-02.huan.tv is in the ACTIVE state. At this time, access using spark-shell will occur. WARN error report


> @lucasbak After HDFS turns on high availability, WARN will be reported every time spark3-shell is executed, but it does not affect the subsequent execution of SQL. How to solve this problem?
> 
> ACTIVE NAMENODE：ali-odp-test-02.huan.tv STANDBY NAMENODE：ali-odp-test-01.huan.tv
> 
> Each time it is executed, it will first access the namenode of the ali-odp-test-01.huan.tv node to see if it is in the ACTIVE state. If not, it will access the namenode on ali-odp-test-02.huan.tv.
> 
> Before turning on high availability, ali-odp-test-01.huan.tv was the NameNode, and ali-odp-test-02.huan.tv was the SecondaryNameNode.
>

**Comment by SGITLOGIN** [comment]
@lucasbak 
hello，Has this question been reproduced？

**Comment by SGITLOGIN** [comment]
@lucasbak 
Is there a way to solve this problem?

**Comment by SGITLOGIN** [comment]
@lucasbak 
Is there any progress on the issue?

**Comment by SGITLOGIN** [comment]
@lucasbak 
Hello, brother, please give me a reply whether the spark-shell WARN alarm problem has been solved or not, thank you.
The prerequisite for this problem to occur is to enable kerberos authentication.

> @lucasbak After HDFS turns on high availability, WARN will be reported every time spark3-shell is executed, but it does not affect the subsequent execution of SQL. How to solve this problem?
> 
> ACTIVE NAMENODE：ali-odp-test-02.huan.tv STANDBY NAMENODE：ali-odp-test-01.huan.tv
> 
> Each time it is executed, it will first access the namenode of the ali-odp-test-01.huan.tv node to see if it is in the ACTIVE state. If not, it will access the namenode on ali-odp-test-02.huan.tv.
> 
> Before turning on high availability, ali-odp-test-01.huan.tv was the NameNode, and ali-odp-test-02.huan.tv was the SecondaryNameNode.
>

**Comment by lucasbak** [comment]
Hi @SGITLOGIN ,

Sorry for the delay, We are working on best effort for the github issues.
You need to update the hdfs-log4j.properties to silence the warning

Best regards

**Comment by SGITLOGIN** [comment]
@lucasbak 
Hello, I changed all the locations where log levels are configured in HDFS to ERROR, but it still didn’t take effect, please analyze this issue again, thank you.

<img width="1333" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/5bec84b6-5417-42ab-b46d-171538643df8">

<img width="1301" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/58bd17a9-4a1c-442e-bb71-26da1b894d0a">

**Comment by SGITLOGIN** [comment]
@lucasbak 
Hello, modifying the log level of HDFS does not take effect, and the problem still exists

**Comment by lucasbak** [comment]
Hi @SGITLOGIN ,

Did you try modifiying log4j properties on spark-client side ? ie in Ambari > Spark[2/3] > configs > log4j properties ?

**Comment by SGITLOGIN** [comment]
@lucasbak 
Changing the Spark log level to Error does not take effect

**Comment by SGITLOGIN** [comment]
@lucasbak 
Is there any progress on this Spark log issue？
