### ISSUE TITLE
When accessing YARNUI, The knox account is not allowed to simulate other accounts.

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#70]
@lucasbak 
Prerequisite: Kebreros authentication is enabled
I configured YARNUI for the Knox service. I followed the official configuration, but when I click to access ApplicationMaster, I get the error "Knox User knox is not allowed to impersonate others.". Is there any other configuration I am missing?

Knox configuration
            <service>
                <role>YARNUI</role>
                <url>http://ali-odp-test-01.huan.tv:8088</url>
            </service>

HDFS configuration
set hadoop.proxyuser.knox.groups to *
set hadoop.proxyuser.knox.hosts to *

YARN configuration
yarn.admin.acl=yarn,knox

Ranger（Knox）
Ranger has been configured so that all users have access (for testing)

<img width="1634" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/79d1575b-3e1e-4884-a74a-99b1810c7993">

<img width="1028" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/6f93c95e-bfdf-4c7d-9b93-ceac9cafe248">

**Comment by SGITLOGIN** [comment]
@lucasbak 
Hello, please reply promptly if there is any progress.

**Comment by SGITLOGIN** [comment]
@lucasbak 
The above problems have been solved

Problem analysis：
When spark webui turns on kerberos authentication, acl permission management requires spark.ui.filters=org.apache.hadoop.security.authentication.server.AuthenticationFilter. However, this configuration will cause the spark history server to fail to start, and hadoop officials have reported this problem. It's a bug（https://issues.apache.org/jira/browse/HADOOP-18750）

Solution：
spark.acls.enable=false
spark.history.ui.acls.enable=false
spark.history.kerberos.enabled=false

Comment out the following configuration
#{% if security_enabled %}
#export SPARK_HISTORY_OPTS='-Dspark.ui.filters=org.apache.hadoop.security.authentication.server.AuthenticationFilter -Dspark.org.apache.hadoop.security.authentication.server.AuthenticationFilter.params="type=kerberos,kerberos.principal={{spnego_principal}},kerberos.keytab={{spnego_keytab}}"'
#{% endif %}

**Comment by lucasbak** [comment]
Hi @SGITLOGIN 

Thanks for the update
By the way in Ambari 2.7.9.0.0-78 we have fixed the issue where Yarn ATS did not start on the first time.

Best regards

**Comment by SGITLOGIN** [comment]
OK
