### ISSUE TITLE
Tez UI Url is not defined

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#76]
@lucasbak 
Hello, does ODP not have its own Tez UI page? Do I need to install Tez UI separately?

<img width="885" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/0d33911d-8f8f-4284-bfb0-e71b11c292d2">

**Comment by lucasbak** [comment]
Hi @SGITLOGIN ,

For now we do not include it, we are checking internally how to integrate it back.

**Comment by SGITLOGIN** [comment]
@lucasbak 
Okay, that means I need to install the Tez UI module myself

**Comment by lucasbak** [comment]
@SGITLOGIN 

Sorry for the delay, yes indeed, it can be done by installing httpd on a TEZ UI node, because we already build tez-ui webapp in ODP

**Comment by SGITLOGIN** [comment]
@lucasbak 
Do you have a reference document for installing TEZ UI?
