### ISSUE TITLE
CentOS8 install ODP failed

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#77]
@lucasbak 
When installing knox, check knox error occurs, but from the final installation result, it appears that the Knox service was successfully installed

installed version: 
https://archive.clemlab.com/centos8/ambari-release/2.7.9.0.0-93/repos-ambari.tar.gz
https://archive.clemlab.com/centos8/odp-release/1.2.2.0-135/repos.tar.gz

operating system:
CentOS 8

<img width="1600" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/01c9461b-e54e-4673-873d-5378c3057176">

**Comment by SGITLOGIN** [comment]
@lucasbak 
Question:
1. Chronyd is installed on the server, but the chronyd service cannot be scanned when installing ambari.
2. CentOS 8 does not have python by default, only python3. However, during the installation process of ambari, python is used instead of python3. I need to execute ln -s /usr/bin/python3 /usr/bin/python
3. There is no distro module during installation, i need to execute pip3 install distro
4. In the installation document on the official website, Getting Ready --> Requirements --> Operating System --> Setup binaries, some of the Setup binaries to be installed on CentOS 8 do not exist in CentOS 8. Finally, the binary files I installed are as follows：
yum install -y curl unzip tar wget gcc* openssl sed openssl-devel openssl krb5-workstation krb5-libs snappy java-1.8.0-openjdk java-1.8.0-openjdk-devel mysql lrzsz httpd openssh-server openssh-clients chrony

<img width="1513" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/1e1f932a-4d5a-455f-8d9b-42d0b63c0921">

**Comment by lucasbak** [comment]
Hi @SGITLOGIN,

Can you try with Ambari 2.7.9.0.0-109

Best regards

**Comment by SGITLOGIN** [comment]
@lucasbak 
The official website has just updated the Ambari installation package link, right?
Is the ODP version not updated?

**Comment by lucasbak** [comment]
Hi @SGITLOGIN ,

Yes its part of the automatic build-test-release process

**Comment by SGITLOGIN** [comment]
ODP version not updated this time?
