### ISSUE TITLE
Ambari UI CSS Issue

### ISSUE THREAD

**Issue by simon4477** [clemlabprojects/ambari#99]
I have the following issue with Ambari Post Installation. The issue is in Chrome and Edge, on Firefox its fine. Please fix the CSS.

![image](https://github.com/user-attachments/assets/0dbd3662-3f27-43c6-af36-ddfb279781e9)

Also, there is no **_Files View_** in HDFS.
![image](https://github.com/user-attachments/assets/7402bbc9-83c2-4520-a350-6aef9a1f42d0)

**Comment by lucasbak** [comment]
Hi,

It is fixed in the latest version
try 2.7.9.0.0-117

Regards

**Comment by lucasbak** [comment]
@simon4477 

does it work ?

**Comment by simon4477** [comment]
Yes, the css issue is fixed in 2.7.9.0.0-117. Thanks @lucasbak :)

**Comment by simon4477** [comment]
@lucasbak in HDP there was a **Files View** in HDFS to browse hdfs files. There is still no **Files View** in ODP Ambari HDFS.

**Comment by lucasbak** [comment]
Hi @simon4477 ,

There is Ambari views however they are not created automatically you need to Go to Admin > Manage Ambari et create the instances.

For now only Capacity Scheduler and Files have been tested.

Regards

<img width="2045" alt="Screenshot 2024-11-19 at 14 42 59" src="https://github.com/user-attachments/assets/835fd6e0-6fc7-49e5-8713-c48cb61b0e4e">

**Comment by simon4477** [comment]
Thanks @lucasbak :) I got it.
